### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by FujiiYuta** [FujiiYuta/accelD#1]
## numpy's 'loadtxt' doesn't work.

> Traceback (most recent call last):
>   File "watchAC_knn.py", line 11, in <module>
>     g = np.loadtxt('wave1.csv', delimiter=',')
>   File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1101, in loadtxt
>     for x in read_data(_loadtxt_chunksize):
>   File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1025, in read_data
>     % line_num)
> ValueError: Wrong number of columns at line 2

**Comment by FujiiYuta** [comment]
the reason why this error is lack of 'wave1.csv' colum. (only line1, col : 2)
